services:
  - type: web
    name: telegram-vpn-bot
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: your_bot_token_here
      - key: DATABASE_URL
        value: postgresql://username:password@host:port/database
      - key: ADMIN_IDS
        value: 123456789
      - key: CARD_NUMBER
        value: 6037-9972-1234-5678
